### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by joedavis** [plan9-for-vimspace/acme-colors#2]
I've a modified version of this theme for personal use that I'd like to publish. If you could clarify the licensing terms for acme-colors, that would be much appreciated.

**Comment by fmoralesc** [comment]
Sure!

**Comment by joedavis** [comment]
Awesome! Thanks for the quick response

**Comment by fmoralesc** [comment]
No problems! Feel free to open a PR to modify the README here if you want to add a link to your version ;)
